const ExercisesData = {
    exerciseNames :  {
        '1': 'Couche haltere',  
        '2': 'Couche haltere 2',
        '3': 'Couche haltere prise serre',
        '4': 'Couche 1 haltere prise serre',
        '5': 'Tajmi3',
        '6': 'Lateral haltere stead',
        '7': 'Piramide',
        '8': 'Couche haltere one hand',
        '9': 'Ecarte haltere',
        '10': 'Incline haltere',
        '11': 'Incline haltere prise serre',
        '12': 'Ecarté incline haltére',
        '13': 'Ecarté incliné haltére 2',
        '14': 'Pullover haltére',
        '15': 'Lateral haltére',
        '16': 'Front chest haltere',
        '17': 'Epaule front + lateral',
        '18': 'Front raise haltére one hand',
        '19': 'Epaule front + lateral 2',
        '20': 'Curl marteau haltére',
        '21': 'Biceps curl haltére',
        '22': 'Curl marteau haltére one hand',
        '23': 'Biceps curl haltére 2',
        '24': 'Biceps curl + marteau',
        '25': 'Biceps curl + avant bras',
        '26': 'Trapéze haltére',
        '27': 'Biceps curl barre',
        '28': 'Biceps curl barre 2',
        '29': 'Biceps curl barre wide grip',
        '30': 'Trapéze barre z',
        '31': 'Laterale barre z',
        '32': 'Front raise barre',
        '33': 'Epaule Front press barre',
        '34': 'Front chest with barre',
        '35': 'Epaule front press 2',
        '36': 'Front raise 1 haltére',
        '37': 'Rowing barre',
        '38': 'Rowing barre 2',
        '39': 'Rowing 2 haltéres',
        '40': 'Oiseaux epaule arriere',
        '41': 'Epaule arriere with barre',
        '42': 'Epaule arriere withe barre 2',
        '43': 'Deadlift',
        '44': 'Avant bras barre',
        '45': 'Avant bras barre 2',
        '46': 'Front raise disc tournant',
        '47': 'Front raise disc',
        '48': 'Epaule front press disc',
        '49': 'Triceps barre z',
        '50': 'Triceps press barre close grip',
        '51': 'Triceps haltere',
        '52': 'Triceps haltere 2',
        '53': 'Triceps barre z incline',
        '54': 'biceps curl haltere short head',
        '55': 'Biceps curl haltere long head',
        '56': 'Epaule arriere haltere',
        '57': 'Spider biceps curl',
        '58': 'Epaule arriere + trapez',
        '59': 'Trapez incliné',
        '60': 'Curl marteau haltere one hand 2',
        '61': 'Triceps 1 haltere 2 hand',
        '62': 'Triceps 1 haltere 1 hand',
        '63': 'Tirage haltere',
        '64': 'Triceps 1 haltere 1 hand 2',
        '65': 'Triage haltere 2',
        '66': 'Couche barre',
        '67': 'Coucher barre wide grip',
        '68': 'Couche barre close grip',
        '69': 'Incline barre',
        '70': 'Decliné barre',
        '71': 'Decliné haltere',
        '72': 'Abdo crunch',
        '73': 'Lombaire',
        '74': 'Triage barre T',
        '75': 'Shoulder press haltere',
        '76': 'Press arnold',
        '77': 'Front chest with cable',
        '78': 'Decline chest with cable',
        '79': 'Vie a vie',
        '80': 'Vie a vie 3 partie',
        '81': 'Press chest with cable',
        '82': 'Cable 2 arms hight row',
        '83': 'Biceps long head with cable',
        '84': 'Biceps curl with cable',
        '85': 'Trapeze with cable',
        '86': 'Avant bras with cable',
        '87': 'Avant bras with cable 2',
        '88': 'Curl marteau with cable',
        '89': 'Triceps with cable',
        '90': 'Epaule arriere with cable',
        '91': 'Triceps press down',
        '92': 'Triceps press down inverse',
        '93': 'Tirage with cable hight row',
        '94': 'Pull over with cable',
        '95': 'Triceps with cable close grip',
        '96': 'Triceps with cable close grip 2',
        '97': 'Pull over with cable close grip',
        '98': 'Triceps with cable one hand',
        '99': 'Epaule arriere with cable one hand',
        '100': 'Triceps with cable one hand 2',
        '101': 'Rowing with cable',
        '102': 'Press machine chest',
        '103': 'Press machine chest close grip',
        '104': 'Tirage with cable machine close grip',
        '105': 'Tirage with cable machine inversé',
        '106': 'Tirage with cable machine wide grip',
        '107': 'Tirage with cable machine one hand',
        '108': 'Lat pull down wide grip',
        '109': 'Lat pull down inversé',
        '110': 'Lat pull down arriere',
        '111': 'Lat pull down close grip',
        '112': 'Lat pull down + epaule arriere',
        '113': 'Hamstring machine',
        '114': 'Leg extension',
        '115': 'Leg extension 1 leg',
        '116': 'Abducteur machine',
        '117': 'Adducteur machine',
        '118': 'Squad',
        '119': 'Langues',
        '120': 'Langues arriere',
        '121': 'Hamstring with barre',
        '122': 'Sumo squad barre',
        '124': 'Front squad with haltere',
        '125': 'Sumo squad with haltere',
        '126': 'Abducteur with disc',
        '127': 'Epaule arriere machine',
        '128': 'Fly machine',
        '129': 'Fly machine 2',
        '130': 'Leg press quadriceps',
        '131': 'Leg press adducteur',
        '132': 'Leg press hamstring',
        '133': 'Leg press mollet',
        '134': 'Stead mollet',
        '135': 'Hack squad',
        '136': 'Machine mollet'
      },

      exerciceVideos : {
        "132": "https://drive.google.com/file/d/1LKe50HZVQ9Nqyp50jWkecr2A7zL4--BM/preview",
        "135": "https://drive.google.com/file/d/1vx6VW9bf3N2axp4tBR8aU5BQVSnV777J/preview",
        "134": "https://drive.google.com/file/d/1ag_x1a16qIWtmnqgbmUTeaCnAhJj8ks4/preview",
        "133": "https://drive.google.com/file/d/1UmBqXJ9-7qyvOpT4NTnc-DqAIrLU90bz/preview",
        "136": "https://drive.google.com/file/d/1reRrH26xOA_b7ssvRrKa52kX9WvTyz36/preview",
        "121": "https://drive.google.com/file/d/1lK1_bGrMMIjUMvsCdcBFojucuW8gNWtf/preview",
        "131": "https://drive.google.com/file/d/1ErY1hBhuutTskyw3o_x5FzPClpbs07nB/preview",
        "126": "https://drive.google.com/file/d/1ADr2BPel1lu3gJWpXHaapF1-TTagjFjK/preview",
        "129": "https://drive.google.com/file/d/1f52I4ziyUcSsr7RjsTOQNDI7GtdLREf_/preview",
        "122": "https://drive.google.com/file/d/1Le-5kDDvIgEgLNIHIUHUHGrWQW2RfRBf/preview",
        "128": "https://drive.google.com/file/d/1Ac5RBOeXCJnGDN31V9QhCVm2897bpELf/preview",
        "124": "https://drive.google.com/file/d/1J_tOuSFNPENQh-0zXitcLDehEZ2INwne/preview",
        "127": "https://drive.google.com/file/d/1oEn7oU-RyYzdybhqUbgfE0x_plpNiJT-/preview",
        "130": "https://drive.google.com/file/d/1dB9DbIUObS5oTRQ553JzrP0Y-ZmuyuG3/preview",
        "125": "https://drive.google.com/file/d/1mTk9EXyyzB7uoR26jkGTp7LwEtNANBl9/preview",
        "116": "https://drive.google.com/file/d/1nni_9QqPpsQiXnl941-Er81XKkB40PXn/preview",
        "118": "https://drive.google.com/file/d/11cgbo1Pd9YjkKz777GEigL6NC6G9VZ90/preview",
        "111": "https://drive.google.com/file/d/1axZB_jc3suipw_KV9h2aTJJDGKkWhsm0/preview",
        "115": "https://drive.google.com/file/d/1oucwuHJhRG0H7WcYuF8eDU9QYDosF10V/preview",
        "119": "https://drive.google.com/file/d/1b40qn8FPY6fdaVtBTr3so_B_fGfihk1_/preview",
        "120": "https://drive.google.com/file/d/1W5ZStEEriMZ31ERpF75sCYfyrZ831qPN/preview",
        "114": "https://drive.google.com/file/d/1zAE7t66YUklMDhdbB2G_Spt3SL2Tbx-f/preview",
        "112": "https://drive.google.com/file/d/1GZaeC-Hk0HnBMVMPUtm0GJwSzCfvNmg_/preview",
        "113": "https://drive.google.com/file/d/1LDMTFWG3acIOK_JjrAlbTS37fihaFRQ6/preview",
        "117": "https://drive.google.com/file/d/1W8Rad7PICYg25NCL19jOBn6oe119rmOF/preview",
        "101": "https://drive.google.com/file/d/1HbGQkqryOxO8uLt7UVP0R_TvcNnDiV31/preview",
        "102": "https://drive.google.com/file/d/1JuDqsTLL1PKeLzh7NfmdXnnXR_miixSx/preview",
        "106": "https://drive.google.com/file/d/1cbxBH5iQbfwt1R1DQ0yGJcR51tOuLJdR/preview",
        "105": "https://drive.google.com/file/d/1NHNBfjBc9mfNkWxK1cELk2JG-Ee1UljB/preview",
        "107": "https://drive.google.com/file/d/1_PfiA5Ix8TI2EhEFTA-kvTD8iafkDpJ0/preview",
        "110": "https://drive.google.com/file/d/1gJspa6ys1j_60W9-7aYDYw2Myzjjy9f9/preview",
        "109": "https://drive.google.com/file/d/1pItN2SSMhZb_ToUWEUfYnyS_UwKIsvx6/preview",
        "100": "https://drive.google.com/file/d/1C-6yRejMCh9YTleCLSw8kjghmChzs1qB/preview",
        "99": "https://drive.google.com/file/d/1pj3OIeEH-Y0PG01NCHgJFJh_GYWp-Nrk/preview",
        "108": "https://drive.google.com/file/d/1Fbdqg1hwf2AEz2zPG4I8h-DP3os2eSrR/preview",
        "98": "https://drive.google.com/file/d/1Z8SMMokus2SYAM8QQpFYlNSh5Hfz8BaO/preview",
        "104": "https://drive.google.com/file/d/13kysX-vIRurPVTEZWQGNGPcVg6ctfZ9b/preview",
        "97": "https://drive.google.com/file/d/1THOUupjxKO10B52Xitj-aOFxMZmD8rwr/preview",
        "103": "https://drive.google.com/file/d/18d72xsIU7ng5nS9OllnM1DhL6EAK0_gY/preview",
        "93": "https://drive.google.com/file/d/1GoQrutc98x19GN576Kyg5tkFXhMWDIcL/preview",
        "88": "https://drive.google.com/file/d/17t9Gxo9Wt0QqW8QqEV-5ZgSDKv_n8Xyp/preview",
        "94": "https://drive.google.com/file/d/10y3WbyvDw3jnQ0sjVMxpFvtQZBvRdDfA/preview",
        "96": "https://drive.google.com/file/d/1RXxE9qxCJdQUIj5kwg1YUWmrbZCY89Vw/preview",
        "95": "https://drive.google.com/file/d/1P8oJwMkTYrWZ5BHiQTw3g-D5EJrduRO5/preview",
        "87": "https://drive.google.com/file/d/1xNBPevjllrRxhA7vs_BrKbLdleLZofVg/preview",
        "90": "https://drive.google.com/file/d/1LsuILNJ9KkTO2MGYLGAlRmuRJyA2Jspz/preview",
        "80": "https://drive.google.com/file/d/1_XTydlopgbJ7OE57bqA2LHov9henr4Ll/preview",
        "91": "https://drive.google.com/file/d/1bhWOx9-IBak656DiE90kLAoTqHU37FKj/preview",
        "84": "https://drive.google.com/file/d/1FJJMowRqVqVN7BZiGL48iUjxEt0lxA9Y/preview",
        "89": "https://drive.google.com/file/d/1iy6r7F6DIZBzp0_N9jMAdrYQsgEp8vhI/preview",
        "92": "https://drive.google.com/file/d/1BpjmzQo2pumRAZBfLM3dAZU5usVjQzRr/preview",
        "86": "https://drive.google.com/file/d/12YNV2dyC9tL4kL_uQHV0P82lwQ8o-pt_/preview",
        "81": "https://drive.google.com/file/d/13zjUeZ4iFaoXt9gezyaIe4XhN9iXwjKe/preview",
        "83": "https://drive.google.com/file/d/1mIUreycbO-hrC0pSBtdj5_kFBH1lkC5A/preview",
        "85": "https://drive.google.com/file/d/1qCMBhHLujVhXo9ZCJElkwGH1pbURj67o/preview",
        "75": "https://drive.google.com/file/d/1lcr3r07n5ndyV54oWi8JHmTtZVWeAo3m/preview",
        "82": "https://drive.google.com/file/d/18HxHQvOOMSRtTuHIVQq2dV5P9zp_o0oE/preview",
        "79": "https://drive.google.com/file/d/1Gy9DJHlsPZfiAaV7MuEZyHepIm5dWbiR/preview",
        "69": "https://drive.google.com/file/d/1zzdE6ttdu1xoFhTWfw2rShE5_IkFYut6/preview",
        "74": "https://drive.google.com/file/d/1LU2X4YHdJaiUtNTO_Pnnbq5-CyaXJ9jU/preview",
        "77": "https://drive.google.com/file/d/12LZ4ldhixbkpy0m9J-rS-KTnrvn0uY1m/preview",
        "68": "https://drive.google.com/file/d/1yXIpKXHN1mXdfUQKHDr6cRuTrdR1VzAQ/preview",
        "78": "https://drive.google.com/file/d/1g0PtYO90s2_ksVmornmME_ywZmxdi64b/preview",
        "76": "https://drive.google.com/file/d/1pfakbV3plshW-jN8S9Hbeer1BGXKBkAS/preview",
        "70": "https://drive.google.com/file/d/1MD2bbpRDF-3YAa8NHIV3w7K3J-HY1HGJ/preview",
        "63": "https://drive.google.com/file/d/14LjiAGPF8LGWa-YFWCceJ69Nm1gC356m/preview",
        "66": "https://drive.google.com/file/d/13lKQCOdAEDNoBwpzd3CGL8Mm91pzVu3b/preview",
        "72": "https://drive.google.com/file/d/1p-zh61yNMA_2OAH_PVnN6E70Dcn-b4UG/preview",
        "64": "https://drive.google.com/file/d/1mj-25PEi_8xs1tnULfN_M2EYtVMMhLvy/preview",
        "56": "https://drive.google.com/file/d/1m-SuYRpkeQ7uNrogN3JHf4mNV4rrLv6L/preview",
        "71": "https://drive.google.com/file/d/1woSJrMc30opEiPHwJTPgwhi4on6TwNLw/preview",
        "73": "https://drive.google.com/file/d/10FzIAdZAHmkgQvQSh5xufO5mdkoOrbN1/preview",
        "65": "https://drive.google.com/file/d/1o39pzfQvLyQyQDEju6JLPpFO-15QsdHG/preview",
        "67": "https://drive.google.com/file/d/1gcxqSXLJ1KVKRXsniWFjkDvSRfkHpbz7/preview",
        "62": "https://drive.google.com/file/d/1mRE-_Eg9HYz_uHj1TlrYpV1qoMW5uBDP/preview",
        "50": "https://drive.google.com/file/d/1MufT7MkNTsc3xYMRZh4dW1iiw-yGhxUu/preview",
        "59": "https://drive.google.com/file/d/1M9HZ98O3DKrsW-NUZOTPF7e5oyJx_hSc/preview",
        "57": "https://drive.google.com/file/d/1faiaTI6-fp_IswABGVO4t_VcshkYcz8-/preview",
        "52": "https://drive.google.com/file/d/1Nsw2JcJKj-0bFEPiBALhU1CX1tXZl4c6/preview",
        "61": "https://drive.google.com/file/d/1PQWzqsxLbJcTAB81w0iStybxZn-L3O6W/preview",
        "51": "https://drive.google.com/file/d/1Z0UjgRcBjNGaz8OsPMMwmhiH0Cv2rVKZ/preview",
        "54": "https://drive.google.com/file/d/13KWmMDEfPnuE0ZuGxUxR_K6E5P-9WlrG/preview",
        "60": "https://drive.google.com/file/d/1xRi4kNPnzVeGX34YVgMczVOhZKZJu3F-/preview",
        "58": "https://drive.google.com/file/d/1w32LNnDlFNpX1nUlYwjE4AnxNK68gl-s/preview",
        "53": "https://drive.google.com/file/d/1wHJDiHDGJ-g6tOgG7k27A8uZ6vQPwC8x/preview",
        "44": "https://drive.google.com/file/d/1BMnyB614QZZlHecJmY9lxRzczbAMLGsz/preview",
        "46": "https://drive.google.com/file/d/1ErqRcHLUTAnicQ842yIWiYpvu7sNMoEL/preview",
        "39": "https://drive.google.com/file/d/1BjySHIk0S_K16i3co2j6oVaGyzJ2zYXa/preview",
        "48": "https://drive.google.com/file/d/1P2-t_uxmyy7TJ8B6iBz5jmSpO1X76yfc/preview",
        "45": "https://drive.google.com/file/d/1EQghLNJgwLPftie5rsr-Iv2MjVnJe6Hz/preview",
        "37": "https://drive.google.com/file/d/1jfPuw3wjQq2ZpEyhOpDYpKZXh9p2y7Qu/preview",
        "38": "https://drive.google.com/file/d/1UvLZLsw4aVih8KVB2KPZ1G8GOsloX93m/preview",
        "55": "https://drive.google.com/file/d/1u-hLlcIuyedxzgLufC_c__wmgFc9dhUs/preview",
        "49": "https://drive.google.com/file/d/1KJNrSVqRwUWHJ_SMqOvEbJFTUKoxHOma/preview",
        "47": "https://drive.google.com/file/d/1FmvmYjPPHYH1zc3KQmWz732XYnmm59-v/preview",
        "31": "https://drive.google.com/file/d/1YyyalqxSfc8zOqRichcM58lE3sbv6Syq/preview",
        "43": "https://drive.google.com/file/d/1UqMLasWCitE-9zob9gHTqEt9oZxN4Lyv/preview",
        "42": "https://drive.google.com/file/d/1nQeIdsddD95JeJZD4BKJtiZQRNj22zo3/preview",
        "36": "https://drive.google.com/file/d/1rGitDGKqYnWBMGyzTEW_Sb_ZFdWLmszB/preview",
        "40": "https://drive.google.com/file/d/1T01x9oOhkrytf0-E7Uxg55cyGbgKVXxf/preview",
        "34": "https://drive.google.com/file/d/110QJMqom9JJyJ3KSqhSD6h6AJuxN92To/preview",
        "41": "https://drive.google.com/file/d/1MAycBKEBkjyRfC9kGbbCtzgq1X7DM2vc/preview",
        "35": "https://drive.google.com/file/d/1Bgp-CVlaQpLeptTye86KKatC2f4TFA5a/preview",
        "33": "https://drive.google.com/file/d/17A6w_U1UG1S5UQfic5KdHXy7a5NdJK_c/preview",
        "32": "https://drive.google.com/file/d/1H41AeBzHfnPiOTTZZhf6B3gMUC3HvQoF/preview",
        "23": "https://drive.google.com/file/d/1Cmqk70YqgAFDYX6xaMtbnx-G8bLMu_ou/preview",
        "27": "https://drive.google.com/file/d/1sb0gfwQHQSzzIGGV_qsQIFwtMFxt0nnn/preview",
        "25": "https://drive.google.com/file/d/1MbcDFroZeBiejCjaQG_btcA386GII_h8/preview",
        "29": "https://drive.google.com/file/d/1xdA01UOQ7BUPGkLYICnhpT_jRLtMS12o/preview",
        "26": "https://drive.google.com/file/d/1F9X3htD_wUXhgV43OJdfjl_5I1KufizL/preview",
        "22": "https://drive.google.com/file/d/1O5NApP_FHDkf3g1CyphgWJlLlASlrpSa/preview",
        "28": "https://drive.google.com/file/d/18rQlhVk_FCLmItplysHXg3jo7DG5rTkV/preview",
        "21": "https://drive.google.com/file/d/1oSMarRgfgzScf62eOeAZjgJOuQPR_IPv/preview",
        "30": "https://drive.google.com/file/d/1X9Vdk5nHaLD6GvcTfX6nIpnjzqL1GCSq/preview",
        "24": "https://drive.google.com/file/d/1Vv3ZZL7kTYD0BX1MN3Ux2HbJ5tLEnJl7/preview",
        "17": "https://drive.google.com/file/d/1_VuSy-LfghNMecc6VXDD6NRkW2lcuaTJ/preview",
        "14": "https://drive.google.com/file/d/1UeVs7mOZhxxix21Z38zYfEzqWE3STEnH/preview",
        "13": "https://drive.google.com/file/d/1b-hCQH43ff3TU2yUmlXoMgYzRBYiMDxN/preview",
        "20": "https://drive.google.com/file/d/1vcieu_my6_aIqkz3W-sF5j7bJnvjZlFc/preview",
        "12": "https://drive.google.com/file/d/1D7TbhnhkXzdpU2PERMJvPt0Oj_6lg8XV/preview",
        "19": "https://drive.google.com/file/d/1yzAfPIatRIThYEhAXUOesQG517oPQLDf/preview",
        "18": "https://drive.google.com/file/d/1F9Z51cK0uowja7v7YkYUrKm1ODMByxDS/preview",
        "15": "https://drive.google.com/file/d/1dQ2HOjo4MQZQ5ffy15vRqKA10AXc9s8f/preview",
        "11": "https://drive.google.com/file/d/1foJSIthRUk86J2_DOCimOBXPpheKmfNJ/preview",
        "16": "https://drive.google.com/file/d/1yr8yVUNNpBPFuvJF1wtsaSuVQ4cKBiDO/preview",
        "10": "https://drive.google.com/file/d/1P5RpyiS1aeBGylDaWeDCaGfzdIdrM-G-/preview",
        "5": "https://drive.google.com/file/d/1eCrVdtFiz80nQbCgj3x9HVQDYgLZSXxb/preview",
        "2": "https://drive.google.com/file/d/1iWuKuVZSH-qMxyaQWfuQdImGzEeAAVc8/preview",
        "8": "https://drive.google.com/file/d/1nsGe8JP-vB9dNCPEqd8uprdaqogI_iMF/preview",
        "9": "https://drive.google.com/file/d/1Lr6RE1nyD-sGVocmhzNyg0hmJNBxXjxH/preview",
        "3": "https://drive.google.com/file/d/1UW2XbKuGxZLbKrrYvpvCJZh2M-BVxp_V/preview",
        "7": "https://drive.google.com/file/d/1d4Pe9hwNYNBsD0f7Q3wy6ovjAqcZnIZR/preview",
        "6": "https://drive.google.com/file/d/1zuUjv_AiUkX2wNZRQHBfPwPdJ0wf3Bhu/preview",
        "1": "https://drive.google.com/file/d/1p2M_VcHTY8lAvZFrY8z9xNv_O2QiShd3/preview",
        "4": "https://drive.google.com/file/d/1yAhdpOmGSymKUHEfc9-hB8aGqcbQtjey/preview"
    }
}

export default ExercisesData